name: Example

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  
    # A workflow run is made up of one or more jobs that can run sequentially or in parallel
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # run something 
      - name: build docker 
        run: |
          pip install pytest
          docker build --tag python-docker . -f tests/Dockerfile
          docker images
          docker run -d -p 5000:5000 python-docker
          docker ps  
          pytest